config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'
  post "reads/createrecipe", to: "reads#create_recipe"
  resources :users, only: [:show] # ユーザーマイページへのルーティング
    resources :posts
    resources :foods
    resources :reads
    root 'hello#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
    belongs_to :user
end

app/models/foodstuff.rb
class Foodstuff < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
        has_many :posts
        has_many :foods
        validates :name, presence: true #追記
        validates :profile, length: { maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    def after_sign_out_path_for(resource)
        root_path
    end
    protected
    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
    before_action :authenticate_user!
    def index
        
        @today = Date.today
        if params[:search] == nil 
            @foods = current_user.foods.order("limit_date")
        elsif params[:search] == ''
            @foods = current_user.foods.order("limit_date")
        else
            @foods = current_user.foods.where("name LIKE ? ",'%' + params[:search] + '%').order("limit_date")
        end
        @num = @foods.size
        @array = Array.new(@num, true)
    end
    def new
        @food = Food.new
        @foods = Foodstuff.pluck(:name).join(",")
    end
    def create
        food = Food.new(food_params)
        food.user_id = current_user.id
        if food.save
          redirect_to user_path(current_user.id)
        else
          redirect_to :action => "new"
        end
    end
    def edit
        @food = Food.find(params[:id])
    end
    def update
        food = Food.find(params[:id])
        if food.update(food_params)
            redirect_to user_path(current_user.id)
        else
            redirect_to :action => "edit", :id => params[:id]
        end
    end
    def destroy
        food = Food.find(params[:id])
        food.destroy
        redirect_to user_path(current_user.id)
    end
      private
      def food_params
        params.require(:food).permit(:name,:num,:limit_date,:deadtime,:price,:where)
      end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def index
    end
    def link
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
    def index
      if params[:search] == nil 
        @posts = Post.all
      elsif params[:search] == ''
        @posts= Post.all
      else
        @posts = Post.where("body LIKE ? ",'%' + params[:search] + '%')
      end
      
    end
    def new
        @post = Post.new
    end
    def create
        post = Post.new(post_params)
        post.user_id = current_user.id
        if post.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end
      private
      def post_params
        params.require(:post).permit(:body)
      end
end

app/controllers/reads_controller.rb
class ReadsController < ApplicationController
    def index
        @foodstuffs = Foodstuff.all
        @recipe = Recipe.all
    end
    def create
        foodstuff = Foodstuff.all
        foodstuff.destroy_all

        xlsx = Roo::Excelx.new('app/assets/excel/food.xlsx')
        sheet = xlsx.sheet('食材名')

        i = 0
        loop do
            i = i + 1
            @foodstuff = Foodstuff.new
            @foodstuff.name = sheet.cell(i,1)
            unless @foodstuff.name.present?
                break
            end
            @foodstuff.save
        end
        redirect_to reads_path
    end
    def create_recipe
        recipe = Recipe.all
        recipe.destroy_all

        xlsx = Roo::Excelx.new('app/assets/excel/food.xlsx')
        sheet = xlsx.sheet('料理レシピ')

        i = 1
        loop do
            i = i + 1
            @recipe = Recipe.new
            @recipe.name = sheet.cell(i,1)
            @recipe.materials = [sheet.cell(i,2),sheet.cell(i,3),sheet.cell(i,4),sheet.cell(i,5),sheet.cell(i,6),sheet.cell(i,7),sheet.cell(i,8),sheet.cell(i,9),sheet.cell(i,10),sheet.cell(i,11)].join(",")
            unless @recipe.name.present?
                break
            end
            @recipe.save
        end
        redirect_to reads_path
    end
    def foodstuff_params
        params.require(:foodstuff).permit(:name)
    end
    def recipe_params
        params.require(:recipe).permit(:name,:materials)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
        foods = @user.foods.pluck(:name)
        recipes = Recipe.all
        @teian = {}
        recipes.each do |r|
            if (r.materials.split(",") & foods).length != 0
                @teian[r.name] = (r.materials.split(",") & foods).length
            end
        end
        @foods = @user.foods.order("limit_date")
        @num = @foods.size
        @array = Array.new(@num, true)
        @today = Date.today
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reads_helper.rb
module ReadsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/edit.html.erb
<h1>編集</h1>
<%= form_for @food do |f| %>
    <p>商品名</p>

    <p>食材名</p><%= f.text_field :name, :size => 140 %>
    <p>数量</p><%= f.number_field :num, :size => 140 %>個
    <p>賞味期限</p><%= f.date_field :limit_date, :size => 140 %>
    <p>値段</p><%= f.number_field :price, :size => 140 %>円
    <p>購入場所</p><%= f.text_field :where, :size => 140 %>

  <%= f.submit "Postする" %>
<% end %>
<%= link_to "Post一覧に戻る", posts_path %>

app/views/foods/index.html.erb
<h3>食材を検索</h3>
    <%= form_tag({controller:"foods",action:"index"}, method: :get) do %>
    <%= text_field_tag :search %>
    <%= submit_tag '検索する'  %>
    <% end %>

<h2>家にある食材</h2>
<% count_t = 0 %>
<% @foods.each do |t| %>
    <% count_t += 1 %>
    <% if @array[count_t - 1] == true %>
        <% @array[count_t - 1] = false %>
        <div>
            <%= t.name %>
            <%= t.num %>
            <%= t.limit_date %>
            <%= (t.limit_date - @today).to_i %>日
            <%= t.price %>
            <%= t.where %>
            <%= link_to "編集", edit_food_path(t.id) %>
            <%= link_to "削除", food_path(t.id), method: :delete %>
        </div>
        <% count_u = 0 %>
        <% @foods.each do |u| %>
            <% count_u += 1 %>
            <% if t.name == u.name && t.id != u.id %>
                <% @array[count_u - 1] = false %>
                <div>
                    <%= u.name %>
                    <%= u.num %>
                    <%= u.limit_date %>
                    <%= (u.limit_date - @today).to_i %>日
                    <%= u.price %>
                    <%= u.where %>
                    <%= link_to "編集", edit_food_path(u.id) %>
                    <%= link_to "削除", food_path(u.id), method: :delete %>
                </div>
            <% end %>
        <% end %>
    <% end %>
<% end %>


<%= link_to "投稿一覧に戻る", posts_path %>

app/views/foods/new.html.erb
<div class="border">

<div class="information">
  <h1 class="food_post">Food Post</h1>
  <%= form_for @food do |f| %>
    
      <div class="box">
      食品名
      <%= f.text_field :name, id:"foodname", required: true%>
      </div>

      <div class="box">
      数量
      <%= f.number_field :num,required: true%>個
      </div>

      <div class="box">
      賞味期限
      <%= f.date_field :limit_date,required: true%>
      </div>

      <div class="box">
      価格
      <%= f.number_field :price,required: true%>円
      </div>
      
      <div class="box">
      購入場所
      <%= f.text_field :where,required: true%>
      </div>

    <%= f.submit "投稿する" %>
  <% end %>
</div>
<input type="hidden" id="title" value="<%= @foods %>">
<script>
    $( function() {
        const title = document.getElementById('title').value.split(",")
        console.log(title)
        var places = title;
        $('#foodname').autocomplete({
            autoFocus: true,
            source: places,
            minLength: 1
        });
    });
</script>

app/views/hello/index.html.erb
<header id="header">
    <h1 class="title">Food-iary</h1>
    <div class="scrolldown4"><span>Scroll</span></div>
</header>
<ul class="sample">
    <li></li>
    <li></li>
    <li></li>
    <li></li>
</ul>


<div id="container">
    <div class="top-container">
        <div class="col-2">   
            <div>
                <img src="../assets/g0940.png" class="ttl" alt="with Picnic">
            </div>
            <div>
            <h3>仕事や勉強、家事で毎日忙しいあなたに。<br>
                Food-iaryで食生活の記録を。<br>
                家にある食材を使って、満足感たっぷりな料理を。<br>
                健康で豊かな生活を送れますように。
            </h3>
            </div>
        </div>
    </div>
    <div class="wrap">
        <ul class="slideshow">
            <li class="content"></li>
            <li class="content"></li>
            <li class="content"></li>
            <li class="content"></li>
        </ul>
        <ul class="slideshow">
            <li class="content"></li>
            <li class="content"></li>
            <li class="content"></li>
            <li class="content"></li>
        </ul>
        <ul class="slideshow">
            <li class="content"></li>
            <li class="content"></li>
            <li class="content"></li>
            <li class="content"></li>
        </ul>
    </div>
        <p></p>    
</div> 

<div id="color_box">
    <div id="colorcontainer">
        <div id="number">01</div>
        <div id="title">Title</div>
        <div id="body">内容書くところ</div>
        <div id="image"></div>
    </div>
</div>

<script>
    const color_box = document.querySelector('#color_box')
    const container = document.querySelector('#colorcontainer')
    const title = document.querySelector('#title')
    const number = document.querySelector('#number')
    const body = document.querySelector('#body')
    const image = document.querySelector('#image')
    window.addEventListener('scroll', () => {

        if (window.scrollY > 1780) {
            container.style.position = 'fixed'
        }else{
            container.style.position = 'relative'
        }
        if (window.scrollY < 3855) {
            title.textContent = "まずは食材を登録してみよう"
            number.textContent = "O1"
            body.innerText = "食材名、個数、賞味期限を入力すると一覧になって表示されます。"
            image.className = "image1"
        }else if (window.scrollY < 5930){
            title.textContent = "マイページで賞味期限を確認しよう"
            number.textContent = "O2"
            body.innerText = "マイページにログインすると、賞味期限間近の食材を通知してくれます。\n食品ロスの削減につなげましょう。"
            image.className = "image2"
        }else if (window.scrollY < 8005){
            title.textContent = "自宅にある食材からつくれるレシピを提案"
            number.textContent = "O3"
            body.innerText= "毎日仕事や勉強、家事で忙しいあなたに。\n買い物に行かず、家にある食材でつくれるレシピを提案します。"
            image.className = "image3"
        }else{
            title.textContent = "「食」を管理してハッピーに"
            number.textContent = "O4"
            body.innerText = "健康的な食事を楽しみましょう。\nFood-iaryがあなたの毎日を彩りますように。"
            image.className = "image4"
        }})
</script>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Food-iary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.2.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  </head>

  <body>
  <div class="main">

  <header>
  <h1 class="foodiary">
    <%= link_to "Food-iary", hello_index_path, class:"word" %>
  </h1>
  <nav class="pc-nav">
    <ul class="gnavi">
      <li><%= link_to "HOME", hello_index_path %></li>
      <li><%= link_to "LOG IN", new_user_session_path %></li>
      <li><%= link_to "LOG OUT", destroy_user_session_path %></li>
      <% if user_signed_in? %>
      <li><%= link_to "MY PAGE", user_path(current_user.id) %></li>
      <% end %>
    </ul>
  </nav>
  </header>

    <%= yield %>
  </div>
    <footer>
    <div class="inline-block_test">
    <div id="back">TOP</div>
    </div>
    <div class="inline-block_test">
    <%= link_to "LOG IN", new_user_session_path %>
    </div>
    <div class="inline-block_test">
    <%= link_to "LOG OUT", destroy_user_session_path %>
    </div>
    <div class="inline-block_test">
    <% if user_signed_in? %>
    <%= link_to "MY PAGE", user_path(current_user.id) %>
    <% end %>
    </div>
    <div class="inline-block_test copy">COPYRIGHT©AIRI KAI<br>ALL RIGHTS RESERVED</div>    
    </footer>
  </body>
</html>
<script>
$(function() {
  $('#back').on('click',function(event){
    $('body, html').animate({
      scrollTop:0
    }, 800);
    event.preventDefault();
  });
});
</script>

app/views/posts/index.html.erb
Enjoy Life!
<% if user_signed_in? %>
<%= link_to "マイページへ", user_path(current_user.id) %>　
<% end %>

<h3>食材を検索</h3>
  <%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
  <%= text_field_tag :search %>
  <%= submit_tag '検索する'  %>
  <% end %>

<%= link_to "memo", new_post_path %>
<%= link_to "新規食材投稿ページへ", new_food_path %>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<div class="posts-container">
  <% @posts.each do |t| %>
    <div class="post">
        <%= t.user.email %>
        <%= t.body %>
        <%= t.created_at %>
        <a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="salecontainer">
  <h1>memo</h1>
  <h3>新規投稿</h3>
  <%= form_for @post do |f| %>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_field :body, :size => 140 %>
    </div>
    <%= f.submit "投稿する" %>
  <% end %>
</div>

app/views/reads/index.html.erb
<br>
<%= button_to "食材更新", controller: :reads, action: :create %>
<%= button_to "レシピ更新", controller: :reads, action: :create_recipe %>
<h3>料理レシピ</h3>
<% @recipe.each do |f| %>
    <%= f.name %> <%= f.materials.split(",") %> <br>
<% end %>
<h3>食品一覧</h3>
<% @foodstuffs.each do |f| %>
    <%= f.name %> <br>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="profilecontainer">
  <div class="profile">
    <h1>プロフィール</h1>
    <p>名前 : <%= @user.name %></p>
    <p>メールアドレス : <%= @user.email %></p>
    <p>プロフィール : <%= @user.profile %></p>
    <% if current_user.id == @user.id %>
      <%= link_to "編集する", edit_user_registration_path %>
    <% end %>
    <label for="trigger" class="open_btn"><div class="tabemono">賞味期限が近い食材</div></label>
    <div class="popup_wrap">
      <input id="trigger" type="checkbox" checked=true>
      <div class="popup_overlay">
        <label for="trigger" class="popup_trigger"></label>
        <div class="popup_content">
          <label for="trigger" class="close_btn">×</label>
          <h2>賞味期限間近！</h2>
          <div>
            <table>
              <thead>
                <tr>
                  <td>食材名</td>
                  <td>個数</td>
                  <td>賞味期限</td>
                  <td>期限まで</td>
                </tr>
              </thead>
              <tbody>
                <% @foods.each do |t| %>
                  <%if (t.limit_date - @today).to_i <2 %>
                    <tr>
                      <td><%= t.name %></td>
                      <td><%= t.num %>個</td>
                      <td><%= t.limit_date.strftime("%Y年%m月%d日")%></td>
                      <td><%= (t.limit_date - @today).to_i %>日</td>
                      <td><%= link_to "編集", edit_food_path(t.id) %></td>
                      <td><%= link_to "削除", food_path(t.id), method: :delete %></td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= image_tag 'zyosei.jpg' ,class:'woman' %>
</div>

<div class="postcontainer">
  <div class="post">
    <h2>投稿</h2>
    <% @user.posts.each do |t| %>
      <%= t.user.name %>
      <%= t.body %>
    <% end %>
    <div class="button012 memo">
      <%= link_to "メモ", new_post_path %>
    </div>
    <div class="button012 ingredients">
      <%= link_to "食材登録", new_food_path %>
    </div>
  </div>
  <%= image_tag 'cake.jpg' ,class:'apple' %>
</div>

<div class="foodcontainer">
  <%= image_tag 'yasai.jpg' ,class:'sandwich' %>
  <div class="food">
      <h2>家にある食材</h2>
      <% count_t = 0 %>
      <table>
        <thead>
          <tr>
              <td>食材名</td>
              <td>個数</td>
              <td>賞味期限</td>
              <td>期限まで</td>
          </tr>
        </thead>
        <tbody>
          <% @foods.each do |t| %>
              <% count_t += 1 %>
              <% if @array[count_t - 1] == true %>
                  <% @array[count_t - 1] = false %>
                  <tr>
                      <td><%= t.name %></td>
                      <td><%= t.num %>個</td>
                      <td><%= t.limit_date.strftime("%Y年%m月%d日")%></td>
                      <td><%= (t.limit_date - @today).to_i %>日</td>
                      <td><%= link_to "編集", edit_food_path(t.id) %></td>
                      <td><%= link_to "削除", food_path(t.id), method: :delete %></td>
                  </tr>
                  <% count_u = 0 %>
                  <% @foods.each do |u| %>
                      <% count_u += 1 %>
                      <% if t.name == u.name && t.id != u.id %>
                          <% @array[count_u - 1] = false %>
                          <tr>
                              <td><%= u.name %></td>
                              <td><%= u.num %>個</td>
                              <td><%= u.limit_date.strftime("%Y年%m月%d日")%></td>
                              <td><%= (u.limit_date - @today).to_i %>日</td>
                              <td><%= link_to "編集", edit_food_path(u.id) %></td>
                              <td><%= link_to "削除", food_path(u.id), method: :delete %></td>
                          </tr>
                      <% end %>
                  <% end %>
              <% end %>
          <% end %>
        </tbody>
      </table>
  </div>  
</div>

<div class="teiancontainer">
  <div class="teian">
    <h2>料理提案</h2>
    <% if @teian.length != 0 %>
      <table>
        <tbody>
          <% @teian.sort_by { |_, v| v }.reverse.to_h.each do |k, v| %>
            <tr>
              <td><%= k %></td>
              <td><%= v %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
        <p>提案する料理がありません🥺</p>
    <% end %>
  </div>
  <%= image_tag 'ryouri.jpg' ,class:'dish' %>
</div>